name: UwbpBukkitBridge
main: com.uws.bridge.bukkitcore.BukkitBridgePlugin
version: 1.0.0
api-version: 1.20
author: UnifiedWorldSync
load: POSTWORLD
description: U-WBP v2 bridge plugin for Bukkit servers.
depend: []
