name: UwbpPaperBridge
main: com.uws.bridge.paper.PaperBridgePlugin
version: 1.0.0
api-version: 1.20
author: UnifiedWorldSync
website: https://example.com
load: POSTWORLD
description: U-WBP v2 bridge plugin for Paper servers.
depend: []
